// Code generated by protoc-gen-go. DO NOT EDIT.
// source: intelligence.proto

package proto

import (
	"context"

	"google.golang.org/grpc"
)

// URLClassification URL 분류
type URLClassification int32

const (
	URLClassification_URL_UNKNOWN URLClassification = 0
	URLClassification_STUDY       URLClassification = 1
	URLClassification_PLAY        URLClassification = 2
	URLClassification_NEUTRAL     URLClassification = 3
	URLClassification_WORK        URLClassification = 4
)

// LogAnalysisRequest 로그 분석 요청
type LogAnalysisRequest struct {
	ClientId   string `json:"client_id"`
	ErrorLog   string `json:"error_log"`
	ScreamText string `json:"scream_text"`
	Context    string `json:"context"`
}

// LogAnalysisResponse 로그 분석 응답
type LogAnalysisResponse struct {
	Success      bool    `json:"success"`
	Markdown     string  `json:"markdown"`
	SolutionCode string  `json:"solution_code"`
	ErrorType    string  `json:"error_type"`
	Confidence   float32 `json:"confidence"`
}

// URLClassifyRequest URL 분류 요청
type URLClassifyRequest struct {
	ClientId    string `json:"client_id"`
	Url         string `json:"url"`
	Title       string `json:"title"`
	PageContent string `json:"page_content"`
}

// URLClassifyResponse URL 분류 응답
type URLClassifyResponse struct {
	Success        bool              `json:"success"`
	Classification URLClassification `json:"classification"`
	Confidence     float32           `json:"confidence"`
	Reason         string            `json:"reason"`
}

// AudioChunk 오디오 청크 (STT 스트리밍용)
type AudioChunk struct {
	ClientId   string `json:"client_id"`
	AudioData  []byte `json:"audio_data"`
	SampleRate int32  `json:"sample_rate"`
	IsFinal    bool   `json:"is_final"`
}

// TranscribeResponse STT 응답
type TranscribeResponse struct {
	Success    bool    `json:"success"`
	Text       string  `json:"text"`
	IsFinal    bool    `json:"is_final"`
	AudioLevel float32 `json:"audio_level"`
}

// IntelligenceServiceClient gRPC 클라이언트 인터페이스
type IntelligenceServiceClient interface {
	AnalyzeLog(ctx context.Context, in *LogAnalysisRequest, opts ...grpc.CallOption) (*LogAnalysisResponse, error)
	ClassifyURL(ctx context.Context, in *URLClassifyRequest, opts ...grpc.CallOption) (*URLClassifyResponse, error)
	// SendAppList calls TrackingService on AI server
	SendAppList(ctx context.Context, in *AppListRequest, opts ...grpc.CallOption) (*AppListResponse, error)
	// TranscribeAudio는 스트리밍이므로 별도 구현 필요
}

type intelligenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntelligenceServiceClient(cc grpc.ClientConnInterface) IntelligenceServiceClient {
	return &intelligenceServiceClient{cc}
}

func (c *intelligenceServiceClient) AnalyzeLog(ctx context.Context, in *LogAnalysisRequest, opts ...grpc.CallOption) (*LogAnalysisResponse, error) {
	out := new(LogAnalysisResponse)
	err := c.cc.Invoke(ctx, "/jiaa.IntelligenceService/AnalyzeLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) ClassifyURL(ctx context.Context, in *URLClassifyRequest, opts ...grpc.CallOption) (*URLClassifyResponse, error) {
	out := new(URLClassifyResponse)
	err := c.cc.Invoke(ctx, "/jiaa.IntelligenceService/ClassifyURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *intelligenceServiceClient) SendAppList(ctx context.Context, in *AppListRequest, opts ...grpc.CallOption) (*AppListResponse, error) {
	out := new(AppListResponse)
	// Target the TrackingService exposed by jiaa-server-ai
	err := c.cc.Invoke(ctx, "/jiaa.tracking.TrackingService/SendAppList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
