// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SabotageCommandService_ExecuteSabotage_FullMethodName = "/jiaa.SabotageCommandService/ExecuteSabotage"
)

// SabotageCommandServiceClient is the client API for SabotageCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SabotageCommandServiceClient interface {
	ExecuteSabotage(ctx context.Context, in *SabotageRequest, opts ...grpc.CallOption) (*SabotageResponse, error)
}

type sabotageCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSabotageCommandServiceClient(cc grpc.ClientConnInterface) SabotageCommandServiceClient {
	return &sabotageCommandServiceClient{cc}
}

func (c *sabotageCommandServiceClient) ExecuteSabotage(ctx context.Context, in *SabotageRequest, opts ...grpc.CallOption) (*SabotageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SabotageResponse)
	err := c.cc.Invoke(ctx, SabotageCommandService_ExecuteSabotage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SabotageCommandServiceServer is the server API for SabotageCommandService service.
// All implementations must embed UnimplementedSabotageCommandServiceServer
// for forward compatibility.
type SabotageCommandServiceServer interface {
	ExecuteSabotage(context.Context, *SabotageRequest) (*SabotageResponse, error)
	mustEmbedUnimplementedSabotageCommandServiceServer()
}

// UnimplementedSabotageCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSabotageCommandServiceServer struct{}

func (UnimplementedSabotageCommandServiceServer) ExecuteSabotage(context.Context, *SabotageRequest) (*SabotageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteSabotage not implemented")
}
func (UnimplementedSabotageCommandServiceServer) mustEmbedUnimplementedSabotageCommandServiceServer() {
}
func (UnimplementedSabotageCommandServiceServer) testEmbeddedByValue() {}

// UnsafeSabotageCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SabotageCommandServiceServer will
// result in compilation errors.
type UnsafeSabotageCommandServiceServer interface {
	mustEmbedUnimplementedSabotageCommandServiceServer()
}

func RegisterSabotageCommandServiceServer(s grpc.ServiceRegistrar, srv SabotageCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedSabotageCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SabotageCommandService_ServiceDesc, srv)
}

func _SabotageCommandService_ExecuteSabotage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SabotageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SabotageCommandServiceServer).ExecuteSabotage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SabotageCommandService_ExecuteSabotage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SabotageCommandServiceServer).ExecuteSabotage(ctx, req.(*SabotageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SabotageCommandService_ServiceDesc is the grpc.ServiceDesc for SabotageCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SabotageCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jiaa.SabotageCommandService",
	HandlerType: (*SabotageCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteSabotage",
			Handler:    _SabotageCommandService_ExecuteSabotage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
